# Generated by Django 3.1.2 on 2020-10-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="page",
        ),
        migrations.RemoveField(
            model_name="page",
            name="user",
        ),
        migrations.DeleteModel(
            name="Budget",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
