# Generated by Django 3.1.2 on 2020-10-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("description", models.TextField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Paid"), ("NP", "Not Paid"), ("C", "Canceled")],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.page"
                    ),
                ),
            ],
        ),
    ]
